### ISSUE TITLE
Support for other languages

### ISSUE THREAD

**Issue by nknapp** [jonschlinkert/extract-comments#1]
I would like to use `verb`'s  apidoc-helper to show comments from within Handlebars partials. In the end, a partial is similar to a function. (e.g. it can take parameters)
This is not possible at the moment, because `extract-comments` is tied to the JavaScript comment-syntax.
There are other modules, for example [groc, that support a multitude of languages](http://nevir.github.io/groc/languages.html) and have a library of comment patterns for each language.
I think it should be possible to incorporate such a pattern-list into `extract-comments` as well.

However, before I start working on a pull-request, I wanted to ask whether you think it is a good idea.

**Comment by jonschlinkert** [comment]
I'm definitely open to it, the idea of having a library of comment patterns sounds pretty interesting. I'm very familiar with [handlebars](https://github.com/assemble/handlebars-helpers) too, so having this could be useful to my own projects as well.

**Comment by nknapp** [comment]
If startet a small module [comment-patterns](https://github.com/nknapp/comment-patterns) that contains the start- and end-patterns for comments from `groc`'s language-database. I think the database itself should be in a separate package.
I have not published it yet I might think of another name. Would you want to have commit-rights and/or publish-rights on npm if this would be a dependency of `extract-comments`?

**Comment by jonschlinkert** [comment]
that's great! 

> Would you want to have commit-rights

if you want to add me as a maintainer/contributor that would be fine, thanks for asking.

**Comment by tunnckoCore** [comment]
@nknapp that `comment-patterns` look good as idea, but when I look it's readme, I think it should be with simpler structure.
1. to be just start and end
2. to be most used patterns (most meaningful for the lang)
3. only for multiline patterns?

``` js
{
  'c': ['/**', '*/'],
  'coffeescript': ['###*', '*###'],
  'mustache': ['{{!', '}}']
  'html': ['<!--', '-->']
}
```

some basic map like https://github.com/jonschlinkert/ext-map

**Comment by tunnckoCore** [comment]
then we can base `extract-comments` on the simplest way. try that

``` js
function extractComments (input, array) {
  var len = input.length, i = 0, commentStart = 0, commentNumber = 1
  var raw = '', code = ''
  var o = {start: 0, end: 0, number: 0}
  var res = array ? [] : {}

  while (i < len) {
    var ch = input.charAt(i)
    var prev = input.charAt(i - 1)
    var next = input.charAt(i + 1)
    var post = input.charAt(i + 2)

    raw += ch

    if (prev !== ' ' && ch === '/' && next === '*' && post === '*') {
      o.start = commentStart = i
    }
    if (o.start && prev === '*' && ch === '/') {
      o.comment = raw.slice(commentStart, i + 2)
      o.end = i
    }
    if (o.start && prev === '/' && /[\r\n]+/.test(ch)) {
      o.number = commentNumber++
      array ? res.push(o) : res[o.number] = o

      // resets
      o = {start: 0, end: 0}
      commentStart = 0
    }
    if (hasValue(res)) {
      var last = array ? res[res.length - 1] : res[Object.keys(res).length]
      code = raw.slice(last.end + 1).replace(/^\n*/, '')
      code = code.split('\n\n').filter(Boolean)
      code = code[0]
      if (code) {
        last.code = code.trim()
      }
    }
    i++
  }
  return res
}

console.log(extractComments(input))
```

just extracting comments on "per character basis" and just one regex for testing `[\r\n]` and Im sure we can do the `.code` thing better but that works atm

**Comment by tunnckoCore** [comment]
output

``````
{ '1': 
   { start: 46,
     end: 72,
     number: 1,
     comment: '/**\n * expose `extract`\n */',
     code: 'module.exports = extract;' },
  '2': 
   { start: 102,
     end: 591,
     comment: '/**\n * Extract code comments from the given `string`.\n *\n * ```js\n * var extract = require(\'extract-comments\');\n * extract(\'// this is a code comment\');\n *\n * // pass a callback to process each comment\n * // directly after it\'s parsed\n * var context = require(\'code-context\');\n * extract(str, function(comment) {\n *   comment.context = context(comment.after);\n *   return comment;\n * });\n * ```\n *\n * @param  {String} `string`\n * @return {Object} Object of code comments.\n * @api public\n */',
     number: 2,
     code: 'function extract() {\n  /**\n   * data var\n   */\n  var todo = \'yesh\'\n}' } }
``````

**nested comments not supported, intentionally**

**Comment by tunnckoCore** [comment]
if we have some mapping with common comment patterns we can replace (or even allow passing functions through opts) these checks

``` js
    if (prev !== ' ' && ch === '/' && next === '*' && post === '*') {
      o.start = commentStart = i
    }
    if (o.start && prev === '*' && ch === '/') {
      o.comment = raw.slice(commentStart, i + 2)
      o.end = i
    }
```

**Comment by tunnckoCore** [comment]
@nknapp @jonschlinkert all that without regexes, ough. lol

**Comment by tunnckoCore** [comment]
@jonschlinkert I think `extract-comments` should only extract, `parse-comments` should only parse the given jsdoc comment, and `js-comments` to do the magic with `extract-comments` plus `parse-comments`.

**Comment by nknapp** [comment]
@tunnckoCore I have thought about some of the things you wrote here. Some of the following may be oppionated, but I would like you the consider the following:

1) Performance: I have done some [performance tests](http://jsperf.com/regex-comments) before I started coding the regex-based extractor. I also thought about doing char-wise parsing, but my tests found it to be much slower than regex, so I went for regex.

2) User experience: When I was playing with `verb`, it was just ignoring a apidoc-comment I wrote. It took a while until I found out that comments in starting at the very beginning of a file, are ignore (I assume, because it's most likely a license). Luckily, I took the time to read the source, otherwise I would have discarded `verb` by now. I'm not sure how many users would do this, so I'd rather have `verb` respect more types of comments than less. In the end, the apidoc-helper only displays comments containing a `@api public`. This statement may be a bit oppionated, and I can find arguments against it myself. It's just a feeling that it is better this way.

3) Language restrictions: Keep in mind that there are some languages that do not have multi-line comments (e.g. `bash` and `sql`). So there is a need for single-line-comment support. 
Also, for example in CoffeeScript lines within comments may start with `#` instead of `*`, so that if `parse-comments` would handle the middle-prefix, it would have to know what prefix to remove. If we do not want to create another database of middle-prefixes, this information is best kept in `comment-patterns`. This may again be my oppionion, but think it is better if `extract-comments` returns a unified representation of the comment, so that `parse-comment` can concentrate on parsing `@param`-tags and likewise instead of having to remove the prefix of the comment first.

I am curious what @jonschlinkert thinks about this.

**Comment by tunnckoCore** [comment]
I understand your positions. But @jonschlinkert trying to keep his modules as simple as possible, small, fast and mostly for his use-cases, mostly for js.

> but think it is better if extract-comments returns a unified representation of the comment, so that parse-comment can concentrate on parsing @param-tags and likewise instead of having to remove the prefix of the comment first.

:+1: exactly what im talkin

**Comment by nknapp** [comment]
I may have misunderstood your point, because what you are saying now is something else than what I have understood before.
For example:

``` js
/**
 * A function
 * @param [String} 'aParam` a parameter
 */
function aFunction(aParam) { var someCode = 1; }
```

What do you think should `extract-comment`  extract from the input?

```
/**
 * A function
 * @param [String} 'aParam` a parameter
 */
```

or

```
 * A function
 * @param [String} 'aParam` a parameter
```

or

```
A function
@param [String} 'aParam` a parameter
```

?

Update: Edited second example to be different from first.

**Comment by tunnckoCore** [comment]
I can't see the diff between first and second, but yea they, not the last. It is parse-comments job to do the parsing and striping stars.

**Comment by nknapp** [comment]
Well, then I understood correctly the first time, and I disagree:

Firstly, `extract-comments` in its current state already stripes the stars from the comment. The only change I propose is to add support for more languages and different comment patterns.

Removing the stars in `parse-comments` would mean that `parse-comments` would also need to know about the language-specific comment-patterns. If you stay in JavaScript-land, it is simple, because there is only one pattern (well, actually two, but you are right when you say that `//` will probably not be used for apidoc-comments`. But take bash for example. There is only one type of comment: Lines starting with`#`, so an apidoc-comment would have to look like.

``` bash
# A function
# @param {string} `aParam` a parameter
function aFunction() {
   A=someCode($1)
}
```

whereas in JavaScript it would look like:

``` js
/**
 * A function
 * @param {String} 'aParam` a parameter
 */
function aFunction(aParam) {
    var a = someCode(aParam);
}
```

and in a Handlebars-partial it might be 

``` hbs
{{!
 A function
 @param {String} `aParam` parameter
}}
{{>someCode aParam}}
```

If `extract-comments` returns the whole comment, including delimiters, how should `parse-comments` know whether to remove the leading `#`  or `*` or nothing? It would need another language-database or maybe the same. But since the database must already be accessed by `extract-comments` to find the comments, it can as well return

```
A function
@param {String} `aParam` parameter
```

for all three examples so that `parse-comments` can analyze the @param-tag and the description without having to worry about what language the original code was written in and what characters to extract. That's what I meant by "unified representation of the comment". 

And for the same reason it is not enough for  `comment-patterns` to contain the start- and end-pattern of a comment.

**Comment by nknapp** [comment]
Btw. I have made a benchmark for comparing the speed of PR #2 and #3 with the current version 0.7.3 of extract-comments. I still have to find out why, but PR #3 is about half the speed of 0.7.3
PR #2 is about the same.

**Comment by nknapp** [comment]
I think I know, why #3 is significantly slower in my test: It extracts both `//`\- and `/**  */`-comments from the testdata. In the dataset I used, this is about twice the number of comments extracted by 0.7.3
If I remove the `//`-comments from the database, both setups extract the same comments and take about the same time to do so (with #3 being slightly slower).

You are probably right, only to extract the  "most used patterns (most meaningful for the lang)" .
`//`-comments are rarely used for apidocs in javascript.

**Comment by tunnckoCore** [comment]
omg.. it so easy, lol. `extract-comments` would just extract them, and `parse-comments` would use `extract-comment`. The right place to do these things is in parse-comments and you should use here this `comment-patterns` thing.
And all this is because the naming, because the name of modules. There's no logic something named `extract` to do more than my proposal. As of `parse` is the place to do **every** type of manipulation (like parsing params and stripping stars and `middle` thing) of the already **extracted** data.
And yea, both should use something to determine different comment patterns (maybe comment-patterns as it is currently isn't a right choice, imo).

**Comment by nknapp** [comment]
This is the last thing I will say to this topic. I have thought long if I should say anything at all, because I have actually made my point already and I'm still sticking to it, but still...
In the snippet:

``` js
/**
 * A function
 * @param {String} 'aParam` a parameter
 */
function aFunction(aParam) {
    var a = someCode(aParam);
}
```

the actual "comment" is 

```
A function
@param {String} 'aParam` a parameter
```

All the other parts are code and belong to the language. The comment is exactly the part that is for humans to read and that is part of the language. The `/**` and `*/` is part of the language and allows the javascript-interpreter to determine which parts of the file it should not be interested it. The comment is the part within. Now, we can argue about the `*` prefixes within. Sure, the JS-parser does not care about this part, but the same holds for an human reading the comment and for any JS-doc parser.

My point is: Even with all the discussion about naming modules and whether `extract` should contain logic or not. My example is still just an _extraction_ and not _parsing_. Parsing is the part where you create something machine-readable from the comment.

**Comment by nknapp** [comment]
My second point is, again, that I the interface of `extract-comments` is exactly doing the above already and my PR does not change anything significant about that. It was not the point of this issue to rethink the concept of `extract-comments`, but to provide multi-language support in order to extract comments e.g. from Handlebars-partials.

**Comment by nknapp** [comment]
@jonschlinkert: I've been thinking. Since my PR is actually a complete rewrite of `extract-comments` (I think, except from the test-cases and documentation, they have nothing in common), I might just publish the module myself under a different name, so both packages can co-exist. I'm still working on test-cases and trying different scenarios, so at this point, there probably would be follow-up PRs.

Update: I think I'm done so far. Test-cases for handlebars are added and seem to work. Added docs to the README as well.

**Comment by jonschlinkert** [comment]
>  I might just publish the module myself under a different name, so both packages can co-exist.

No problem at all, honestly you've put so much work into it and it seems like a great lib, I think that makes sense! That decision is totally yours to make!

**Comment by nknapp** [comment]
Glad, you like it. Yes, it was some work, but it put me on interesting paths (such as really making performance tests for different algorithms to solve a problem).
Then I'll close the pull request and make it my own lib. I'll have to check how to integrate it with `parse-comments` since I would need to replace the `require('extract-comments')` with my own library (possible `parse-code-context` as well). But I'll probably make a pull-request there when I have gotten so far.

**Comment by nknapp** [comment]
`npm install multilang-extract-comments`
