### ISSUE TITLE
Custom context parser

### ISSUE THREAD

**Issue by cazzer** [jonschlinkert/extract-comments#10]
I know this comment extractor is meant for JavaScript but I am actually using it for Sass which works well except for the context. I can use the `loc.end.line` comment property to find the right line of context to parse myself, but it would be extra cool if I could pass my own context parser as an option so it can be parsed along side the comment.

I can work on a PR, but I wanted to get your thoughts first.

**Comment by jonschlinkert** [comment]
Great idea, a pr would be great, thanks!

**Comment by jonschlinkert** [comment]
just a heads up, this was just refactored to use esprima for parsing. I created a lib to do SASS comments but haven't published yet (I'm trying to get it working with plugins). you might want to stick with 0.9.0 until then.

**Comment by jonschlinkert** [comment]
closing due to age and lack of response
