### ISSUE TITLE
Empty line comment causes next line to be stripped

### ISSUE THREAD

**Issue by epicoxymoron** [jonschlinkert/extract-comments#11]
This looks similar to #9, but it appears the fix for that may have only targeted block comments, and left line comments still incorrect.

**Fixture**:

``` javascript
//
var foo = "bar";
var baz = "bar";
```

**Expected Result**:

``` javascript

var foo = "bar";
var baz = "bar";
```

**Actual Result**:

``` javascript

var baz = "bar";
```

**Comment by jonschlinkert** [comment]
thanks for reporting.

**Comment by epicoxymoron** [comment]
Upon further investigation, I don't think there's an issue in `extract-comments`, but instead in `strip-comments`.  I was working my way through the chain from `gulp-strip-comments`, trying to find the culprit, and didn't understand the contract well enough of what `extract-comments`'s job was.  I understood "extract" to mean "strip" as opposed to "identify".  My mistake.

In other good news, I think I've got a simple fix for the other codebase.  I'll create an issue on `strip-comments`, and, unless you want to troubleshoot this further here, I'm happy if you want to close this issue.

**Comment by jonschlinkert** [comment]
> In other good news, I think I've got a simple fix for the other codebase. I'll create an issue on strip-comments

that's great, thank you!  I'll close here and await next steps from you.
