### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by shinate** [jonschlinkert/extract-comments#13]
Very useful, I found a problem in use

If an odd number of single quotation mark in a block, the subsequent text will all be recognized as a comment
Terminates in the next block comments to the same rules

``` javascript
/*'balabala''*/
var a = '';
/*'''*/
var b = '';
/* balabala */
var c = '';
```

var a = ''; will be recognized as a comment

``` javascript
/*'*/
```

In this case, all the subsequent code will be lost

**Comment by shinate** [comment]
A pair of quotation marks are converted, but the single did not.
comments may appear "that's right ~"

**Comment by shinate** [comment]
Ohhh ... I saw you change to espree, this will be resolved :D

**Comment by jonschlinkert** [comment]
closing due to age
