### ISSUE TITLE
comment.raw is not correct - seems almost the same as comment.value

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/extract-comments#14]
In the readme is shown that that `.raw` property contain the full comment including starting and ending parts `/*` and `*/`.

The example from the readme isn't correct.

``` js
var str = '/**\n * this is\n *\n * a comment\n*/\n\n\nvar foo = "bar";\n';
var comments = extract(str);
console.log(comments[0].raw)
// => '*\n * this is\n *\n * a comment\n'
// and not '/**\n * this is\n *\n * a comment\n*/'
```

causing errors in `strip-comments` lib, because it tries to `str.replace(comment.raw, '')`.

So we need some real raw, or at least useful character location position. I mean, we can do nothing with that `loc` currently:

``` js
loc: { start: { line: 1, column: 0 }, end: { line: 5, column: 2 } }
```

It's almost useless, because is on per line basis. But we need something like `loc.pos` which would be character position from the beginning of the string/file.

**Comment by tunnckoCore** [comment]
But okey, actually i have idea, to make it work in the `strip-comments` as i do in [acorn-strip-comments/index.js#L142-L147](https://github.com/tunnckoCore/acorn-strip-comments/blob/master/index.js#L142-L147)

**Comment by jonschlinkert** [comment]
> causing errors in strip-comments lib

none of the comments libs have any errors for me. 

> So we need some real raw, or at least useful character location position.

Why is it a problem? everything is correct. All you need to do is prefix raw with `/*` and append `*/`, then use `-2` and `+2` in slice.

**Comment by tunnckoCore** [comment]
> none of the comments libs have any errors for me.

when bump to latest `extract-comments`, the `strip-comments` tests starts to fail.

Nevermind, tweaked.

**Comment by jonschlinkert** [comment]
k thx
