### ISSUE TITLE
Support for other languages / file formats

### ISSUE THREAD

**Issue by andreashuetter** [jonschlinkert/extract-comments#15]
Hi Jon, can we just enhance the extract-comments package a little bit in that manner that it can support other types of comments as well (for example semicolon-comments used in assembly language)?

For instance, we could just augment the options object like this:

```
strip.line(commentString, { lineStart: "//" });
strip.block(commentString, { blockStart: "/*", blockEnd: "*/" });
```

Thus one could simply do

`
strip.line(commentString, { lineStart: ";" });
`

and would be able to extract semicolon-based comments as well.

What do you think?

_Edit:_
I am currently using your npm package strip-comments (v0.4.3) which does not depend on the latest version 0.10.1 of extract-comments, but on an older version 0.8.7 of extract-comments.
In the version 0.8.7 of extract-comments I am able to do the above enhancement by simply changing the following code in index.js
from

```
function block(str, options, fn) {
  return factory('/*', '*/', Block)(str, options, fn);
}

function line(str, options, fn) {
  return factory('//', '\n', Line)(str, options, fn);
}
```

to

```
function block(str, options, fn) {
  return factory(options.blockStart || '/*', options.blockEnd || '*/', 
                 Block)(str, options, fn);
}

function line(str, options, fn) {
  return factory(options.lineStart || '//', '\n', Line)(str, options, fn);
}
```

But regarding the latest version 0.10.1 of extract-comments, I'm not able to find the part of the code where I can perform those changes. Would you mind being so kind to give me a hint on this?

**Comment by jonschlinkert** [comment]
closing due to age
