### ISSUE TITLE
Code that immediately follows a comment isn't captured.

### ISSUE THREAD

**Issue by cazzer** [jonschlinkert/extract-comments#9]
I just submitted a PR #8 for this, but figured I should add an issue to track it if the PR is declined.

Here is the error case:

``` js
/**
 * Some comment
 */
var someCode;
```

`var someCode;` won't be captured as context.

**Comment by jonschlinkert** [comment]
Ah, I know why. will be an easy fix, thanks for reporting

edit: see you did a pr, thanks will review in a few min
